name: Manual Workflow Approval
description: Pause a workflow and get user approval to continue
branding:
  icon: pause
  color: yellow
inputs:
  approvers:
    description: Required approvers
    required: true
  secret:
    description: Secret
    required: true
  minimum-approvals:
    description: Minimum number of approvals to progress workflow
    required: false
  issue-title:
    description: The custom subtitle for the issue
    required: false
  plan:
    descrition: the terraform plan
    required: true
runs:
  using: docker
  image: docker://ghcr.io/pattisd01/manual-approval:2.0.0
